<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TimeClock.Domain\TimeClock.Domain.csproj" />
    <ProjectReference Include="..\TimeClock.Infrastructure\TimeClock.Infrastructure.csproj" />
  </ItemGroup>
</Project>
